### ISSUE TITLE
What is hash size? 

### ISSUE THREAD

**Issue by Jishnu2010** [ShailChoksi/lichess-bot#228]
Hello everyone, I have a question about the config.yml file. I just wanna know that what is that hash size? I mean why is that there? And also at what size should I set it so that my bot becomes stronger? I have these questions. Can anyone tell me the answers?

**Comment by Tearth** [comment]
Hash size option tells your engine how big your transposition table/pawn hash table/evaluation table should be. It doesn't mean that your program can't exceed this value looking at process' memory usage, but it should be approximately similar.

**Comment by Jishnu2010** [comment]
@Tearth I didn't understand.Can you please tell it in a simpler way if you can?

**Comment by zzhangb4** [comment]
"Hash size" (hash table size) refers to how large the engine's transposition tables can be and thus how much memory can be allocated to them. This value should be set in relationship to how many threads you use. 

**A large hash size does not necessarily mean stronger play**, especially in fast time controls such bullet and blitz. Larger hash sizes are better for longer time controls, as the transposition tables can fill completely. I think a hash size of 64 or even 128 is more than enough for a lichess bot.

**Comment by Jishnu2010** [comment]
Is 1024 enough for rapid?

**Comment by zzhangb4** [comment]
Again, I would like to stress the fact that large hash sizes may not necessarily increase play strength, especially in shorter time formats, however there are a few exceptions which affect this (the most obvious of which is CPU strength). Generally, I prefer hash sizes of 64 mb to 128 mb, as they are large enough to make decent searches but are also are small enough to maintain engine strength (I'm using Stockfish 12 with lichess-bot). Example: @BlazikenBot2000 on lichess, it's hosted on free Heroku worker dynos, with Stockfish 12, 1 thread, 128 hash, and performs at a decent strength. 

Anything larger than 256 mb I think is complete overkill, simply because at this point it's just a competition to see **Who Has the Biggest CPU**, and regardless of how much hash you allocate, **there's always going to be someone running lichess-bot on some ridiculously strong hardware**, because that's such a wonderful usage of computing power. When running local chess engine tournaments, it's easy to see the damaging effect of enormous hash sizes in bullet games; however, during online bot chess, it's **difficult to say exactly what the best hash size is**, because there are so many uncontrolled variables at play, ie CPU strength and latency. Personally I recommend nothing more than 256 mb hash. You can use 1024 if you want to, but please make sure it's justified (that means you had better start winning some rapid games!). 

Note: Set hash size after threads. The more threads you use, the more hash you can use. Make sure to check that your PC/Cloud/Pi actually has that many threads, ie don't set 1000 threads when only 4 are available :)

**Comment by Jishnu2010** [comment]
Ok thanks I have got an idea. I am closing this issue.
