### ISSUE TITLE
Question: Ponder Implementation

### ISSUE THREAD

**Issue by TheYoBots** [ShailChoksi/lichess-bot#348]
I was just wondering, liches-bot has implemented a separate ponder (for both UCI and XBoard protocol), which can be used even when th engine doesn’t have a ponder setting or has one that hasn’t been set. Has this been made possible only because python-chess (or rather PyPi package chess) supports it and wouldn’t be possible if python-chess didn’t support?
If it is possible only because of python-chess, does anyone have the particular lines of the code (in python-chess) which provides ponder support?

**Comment by MarkZH** [comment]
Back before the [upgrade to python-chess 1.4](https://github.com/ShailChoksi/lichess-bot/commit/afe4acdc9aa8a42c0ef572c77df5f6e9daaf7013) lichess-bot handled pondering itself, using python-chess only for sending properly formatted commands to the engine. Now, after the [upgrade to python-chess 1.5](https://github.com/ShailChoksi/lichess-bot/commit/4be6f2c3a59c5957660ab204aa292623be926ae1), pondering is completely handled by the python-chess library with lichess-bot only having to send the right `ponder` parameter in the `EngineWrapper.search()` [method](https://github.com/ShailChoksi/lichess-bot/blob/6c41ae28e824b1e5009e55bca999c77585b00355/engine_wrapper.py#L83). This is probably better for us since the python-chess library is very popular and any problems are quickly fixed (plus, the asynchronous programming needed to handle pondering is annoyingly subtle).

For UCI engines, the `go ponder` command is sent [here](https://github.com/niklasf/python-chess/blob/d0b2204b345812e1f212152b4e4880bb1945c453/chess/engine.py#L1620). The actual command gets built [here](https://github.com/niklasf/python-chess/blob/d0b2204b345812e1f212152b4e4880bb1945c453/chess/engine.py#L1493). Notice that the `go ponder` command is only sent if `ponder=True` and the engine returns a `bestmove` statement with a `ponder` move.

For XBoard engines, pondering is [very simple to handle](https://github.com/niklasf/python-chess/blob/d0b2204b345812e1f212152b4e4880bb1945c453/chess/engine.py#L2120):

    engine.send_line("hard" if ponder else "easy")

The command `hard` tells the engine it is allowed (but not required) to ponder, and `easy` tells the engine it is not allowed to ponder. An XBoard interface does not have to care all that much what an engine does while it ponders. All the interface has to do is send the opponent's move (possible with a `usermove` prefix) when the opponent has made a move. In a well-behaving XBoard engine that doesn't support ponder, the engine will just ignore the `hard` command, so there's no problem with an XBoard engine having `ponder` set to true even if it does not ponder.

**Comment by TheYoBots** [comment]
Thanks for those insights. 

I’ve mainly been interested in doing this for [lishogi-bot](https://github.com/TheYoBots/Lishogi-Bot), but can’t be sure it will even work as it does in lichess-bot as lishogi-bot uses python-shogi (https://github.com/gunyarakun/python-shogi / https://pypi.org/project/python-shogi/ ). Python-shogi, though based on python-chess doesn’t support many features such as ponder, tablebases (Hard to implement for games in which you can drop captured pieces, like crazyhouse), variants, opening books, etc. So after receiving a [PR](https://github.com/TheYoBots/Lishogi-Bot/pull/22) I wasn’t really too sure whether it would really make sense to use a variable (`ponder`) that isn’t even supported by the library that to bot is dependent on.

**Comment by MarkZH** [comment]
I think a good model for implementing ponder in lishogi-bot is lichess-bot.py after [the refactor](https://github.com/ShailChoksi/lichess-bot/commit/936c516e5327d01eb7fb16efd4453513a294303a):

https://github.com/ShailChoksi/lichess-bot/blob/936c516e5327d01eb7fb16efd4453513a294303a/lichess-bot.py

After the engine picks a move, start a thread that sends the `go ponder` command to the engine. The thread allows for communication with the pondering engine while waiting for a new move. That appears to be what the linked PR is doing.

**Comment by TheYoBots** [comment]
Thanks a lot for your help! I’ll be closing this issue soon and will merge the PR too. Thanks again!
