### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by SwiftCuber14** [ShailChoksi/lichess-bot#372]
When this code is used to run an engine on a normal account (an account that isn't registered as a BOT) there is an issue because the script runs a test to see if the account is a bot. Does anyone know how to remove this so an engine can run on a normal account. I am not looking to be judged, just looking for advice.

**Comment by AttackingOrDefending** [comment]
Even if you remove the test it will still not work. Why would you want to do this (apart from cheating)? Also, using a chess engine can be detected very easily because they play a lot better than the best chess players. With some changes (beyond just removing the test), I think it will work but I haven't tested it. I would recommend not doing this.

**Comment by SwiftCuber14** [comment]
> Even if you remove the test it will still not work. Why would you want to do this (apart from cheating)? Also, using a chess engine can be detected very easily because they play a lot better than the best chess players. With some changes (beyond just removing the test), I think it will work but I haven't tested it. I would recommend not doing this.

I code because I do not like limitations. When I see a limitation I will try to surpass it. Thank you for informing me of the repercussions but, I am purley asking this to see if anyone can help before I dive in deep and start looking through all the files.

**Comment by MarkZH** [comment]
Nobody is going to help you subvert lichess rules. Practicing programming to get better is a good thing. Practicing to surpass your own limitations is a good thing. But, you do not have the right to use other people's resources without their permission.

An analogy: Learning to pick locks is a good skill to learn. Practicing on locks you own is good. Going to another person's house and picking their locks without their permission is wrong, even if your purpose is not theft.

lichess is very explicit about separating human and engine accounts. From the sign-up page:

> Computers and computer-assisted players are not allowed to play.

From the Terms of Service:

> Do not cheat or receive assistance in games (from a chess computer, book, database or another person).

The lichess site is the product of a lot of work by a lot of people. Please respect their wishes when using the product of their work, especially because it is free to use. If you want to run an engine, make a bot account. Otherwise, stop what you're doing.

**Comment by SwiftCuber14** [comment]
> Nobody is going to help you subvert lichess rules. Practicing programming to get better is a good thing. Practicing to surpass your own limitations is a good thing. But, you do not have the right to use other people's resources without their permission.
> 
> An analogy: Learning to pick locks is a good skill to learn. Practicing on locks you own is good. Going to another person's house and picking their locks without their permission is wrong, even if your purpose is not theft.
> 
> lichess is very explicit about separating human and engine accounts. From the sign-up page:
> 
> > Computers and computer-assisted players are not allowed to play.
> 
> From the Terms of Service:
> 
> > Do not cheat or receive assistance in games (from a chess computer, book, database or another person).
> 
> The lichess site is the product of a lot of work by a lot of people. Please respect their wishes when using the product of their work, especially because it is free to use. If you want to run an engine, make a bot account. Otherwise, stop what you're doing.

Woah dude, It is not my intentions to use this against any player as I never said that. Also when the creator published the code, he gave the users full access to change and alter his code and that is the whole point of GitHub.

**Comment by MarkZH** [comment]
You're right. I responded too harshly. Sorry.

What are you trying to accomplish?

**Comment by SwiftCuber14** [comment]
> You're right. I responded too harshly. Sorry.
> 
> What are you trying to accomplish?

Nevermind, I believe I have found a solution.
