### ISSUE TITLE
Sends draw to UCI engines causing everything to crash. 

### ISSUE THREAD

**Issue by SquarishRectangle** [ShailChoksi/lichess-bot#377]
Draw and takeback requests should be handled in lichess-bot itself and not passed on to the engine as UCI doesn't officially support draws, takebacks, and resigns which wreaks havoc on engines that don't have a custom draw/takeback/resign function.

**Comment by SquarishRectangle** [comment]
Actually I am not sure if that is the exact issue but I'm too lazy to pick though Lc0's horrible logfile. 
This is the logfile
[logfile.log](https://github.com/ShailChoksi/lichess-bot/files/6904159/logfile.log)
and this is the test game. 
https://lichess.org/uDgfttfy

Whatever is the real issue offering a draw completely destroys everything.

**Comment by MarkZH** [comment]
Searching through the log file, I found this line

    0729 19:18:43.275225 12304 c:\projects\lc0\src\chess\uciloop.cc:135] >> position startpos moves b2b3 d7d6 d7d6 e2e3 e7e6

Notice that the move `d7d6` is repeated. The second copy is an illegal move, which is why your engine stops. How recent is your copy of `lichess-bot.py`? Old versions would sometimes have problems with repeated moves when receiving messages from lichess.org that did not contain new moves (like draw offers, for example).

I think this should be fixed by running `git pull` in the lichess-bot directory to get the most recent version.

**Comment by MarkZH** [comment]
If I'm right, you'll have to run `python3 -m pip install -r requirements.txt` again after pulling the latest changes to make sure you have all the required programs.

**Comment by SquarishRectangle** [comment]
@MarkZH That seemed to have fixed it. Thanks!
