### ISSUE TITLE
help pls help 

### ISSUE THREAD

**Issue by barca-cloud** [ShailChoksi/lichess-bot#386]
Traceback (most recent call last):
  File "C:\Users\Tubu\Desktop\THEBESTBOT\lichess-bot-master\lichess-bot.py", line 440, in <module>
    CONFIG = load_config(args.config or "./config.yml")
  File "C:\Users\Tubu\Desktop\THEBESTBOT\lichess-bot-master\config.py", line 10, in load_config
    with open(config_file) as stream:
FileNotFoundError: [Errno 2] No such file or directory: './config.yml'

**Comment by MarkZH** [comment]
Is there a `config.yml` file in the directory C:\Users\Tubu\Desktop\THEBESTBOT\lichess-bot-master\?

**Comment by amanjpro** [comment]
I feel the issues in this repo are abused for seeking help, and not issue tracking.

Does it make sense to have a discord for seeking help, and this only for issues in the code and/or feature request?

**Comment by barca-cloud** [comment]
> I feel the issues in this repo are abused for seeking help, and not issue tracking.
> 
> Does it make sense to have a discord for seeking help, and this only for issues in the code and/or feature request?

WHAT?

**Comment by MarkZH** [comment]
@amanjpro I don't really mind right now since the new issues aren't created all that often. Then again, this isn't my repo. I don't know if a discord channel would be more work since I don't use it. It would be ideal to separate help from code bugs, but its effectiveness would depend on how often people who can help are present in the channel.

@barca-cloud Your past issues have been solved by just reading the error messages. Please try to do more investigating and debugging on your own before asking for help here. For your latest issue (#387), there is nothing we can do with just those error messages. Your engine is not starting. You need to investigate to find out why that is. Turn on verbose output (`python lichess-bot.py -v`); try to run the engine from the command line; change configuration options. If nothing works, then report what you've tried and what happened.
