### ISSUE TITLE
Make sure that online egtb is used if enabled

### ISSUE THREAD

**Issue by TheYoBots** [ShailChoksi/lichess-bot#474]
When the number of pieces is less that 7 (or 6 in variants applicable), playing a move taken from egtb is always the best move. But I've noticed that inspite of enabling online egtb (either source) the bot doesn't always send the logs `Got move {move} from {source}...` when the number of pieces on the board is less than 7 and this results in various endgame mistakes.

Example game(with move number): https://lichess.org/n2vUSsyt/black#173

**Comment by AttackingOrDefending** [comment]
`85. Rg2` is also a move that the egtb wouldn't have played because the wdl went from 0 to -1, so the online egtb was also not used there. My guess is that the bot had less time than `min_time`, so it didn't use the online egtb. The `min_time` parameter was added for games with fast time controls like the one you played (1/2+0), so the bot wouldn't waste a lot of time to get the move from the online egtb, because depending on the internet connection it might even take a second to get the move so the bot might lose on time. Can you send the `online_moves` section of your config.yml and the logs from the game?

**Comment by TheYoBots** [comment]
Thanks!
