### ISSUE TITLE
I need HELP

### ISSUE THREAD

**Issue by FatFritz2** [ShailChoksi/lichess-bot#509]
I want to enable "!eval" for the bot
It says I don't tell that to my opponent, sorry i want to enable the eval tho thanks
And how to make enable matchmaking

**Comment by MarkZH** [comment]
Normally, the bot will not print its evaluations to chats with its opponent because this would give the opponent information about what the bot is thinking. If you are playing against your own bot or logged into your bot's account, you won't be able to see what the bot is thinking with `!eval`.

There are a few things you can do:

1. If you are near the computer that is running the bot, you can run lichess-bot with the `-v` flag to enable verbose output. This will print everything the bot is thinking (along with other messages).
2. You can watch your bot play games on the lichess website or app while logged into your own account. As long as you are a spectator to the game and not a player, you can use the `!eval` command to see your bot's thinking.
3. If you want to see your bot's thinking while playing against it, and option 1 doesn't work, then you need to change some code in lichess-bot.

Go to [line 32 in conversation.py](https://github.com/ShailChoksi/lichess-bot/blob/7b614a228a67d128f20885a2d0a8b17f0c7f7739/conversation.py#L32). Change the line from
```python
        elif cmd == "eval" and line.room == "spectator":
```
to
```python
        elif cmd == "eval" and (line.room == "spectator" or line.username == "FatFritz2"):
```
Use your lichess.org user name if it's not @FatFritz2.

**Comment by MarkZH** [comment]
As for matchmaking, look at the bottom of config.yml.default and the README document. Make sure that you don't set `challenge_timeout` to less than one minute. Otherwise, lichess may stop allowing your bot to make challenges due to making too many requests too quickly.

**Comment by FatFritz2** [comment]
Ok let me see thanks

**Comment by MarkZH** [comment]
Is there a problem?

**Comment by FatFritz2** [comment]
Ah no problems rn thanks
