### ISSUE TITLE
Master (298a98a) is crashing.

### ISSUE THREAD

**Issue by TheBlackPlague** [ShailChoksi/lichess-bot#542]
Please see the following error:
```
                    DEBUG    https://lichess.org:443 "POST connectionpool.py:456
                             /api/challenge/1rS8wjz8/decli
                             ne HTTP/1.1" 404 None
                    DEBUG    Giving up api_post(...) after 1      _common.py:120
                             tries
                             (requests.exceptions.HTTPError: 404
                             Client Error: Not Found for url:
                             https://lichess.org/api/challenge/1r
                             S8wjz8/decline)
```

Moreover... the following stack trace:
```
                    ERROR    Quitting lichess-bot due to an   lichess-bot.py:964
                             error:
                             Traceback (most recent call
                             last):
                               File "/lcbot/lichess-bot.py",
                             line 962, in <module>
                                 start_lichess_bot()
                               File "/lcbot/lichess-bot.py",
                             line 955, in start_lichess_bot
                                 start(li, user_profile,
                             CONFIG, logging_level,
                             args.logfile)
                               File "/lcbot/lichess-bot.py",
                             line 146, in start
                                 lichess_bot_main(li,
                               File "/lcbot/lichess-bot.py",
                             line 239, in lichess_bot_main
                                 li.decline_challenge(chlng.i
                             d, reason=decline_reason)
                               File "/lcbot/lichess.py", line
                             118, in decline_challenge
                                 return
                             self.api_post(ENDPOINTS["decline
                             "].format(challenge_id),
                               File
                             "/usr/local/lib/python3.9/dist-p
                             ackages/backoff/_sync.py", line
                             105, in retry
                                 ret = target(*args,
                             **kwargs)
                               File "/lcbot/lichess.py", line
                             86, in api_post
                                 response.raise_for_status()
                               File
                             "/usr/local/lib/python3.9/dist-p
                             ackages/requests/models.py",
                             line 1021, in raise_for_status
                                 raise
                             HTTPError(http_error_msg,
                             response=self)
                             requests.exceptions.HTTPError:
                             404 Client Error: Not Found for
                             url:
                             https://lichess.org/api/challeng
                             e/1rS8wjz8/decline
```

**Comment by TheBlackPlague** [comment]
This issue may be Lichess related. The bot plays fine vs. fairy-stockfish (on Lichess when using Play with the Computer). Weird issue but prevents the bot from playing games. 😢

**Comment by MarkZH** [comment]
Looking at the error, I'm a bit surprised this hasn't happened before. @AttackingOrDefending would setting `raise_for_status=False` in `Lichess.decline_challenge()` be the correct fix?

**Comment by AttackingOrDefending** [comment]
It will fix this, but I think TheBlackPlague gets this error because they challenge other bots and their bot tries to decline the challenge (I would guess that `accept_bot` is false), causing an error because they can't decline their own challenges. We can add a check for challenges that the bot created and not decline them.
[Here](https://github.com/ShailChoksi/lichess-bot/blob/master/lichess-bot.py#L238) we can change it to:
```python
elif chlng.challenger_name != user_profile["username"]:
```
or we can add this check inside [`is_supported`](https://github.com/ShailChoksi/lichess-bot/blob/master/lichess-bot.py#L231).

After enabling `only_bot`, when I challenged my human account, I got the same error, so this is the cause of the error.

**Comment by MarkZH** [comment]
@TheBlackPlague In order to confirm the problem source, please post your config.yml file with the token deleted. Also, it would help if you could run lichess-bot again with verbose logging and saving to a file (`-l log.txt`). When you get the error again, post the entire log (if the log is very long, you can use https://gist.github.com/) so we can see what happens before the error.

@AttackingOrDefending That diagnosis makes sense. Adding the check to `is_supported()` is best, since any challenge created by the bot should be supported by definition. I still think adding `raise_for_status=False` to `decline_challenge()` would also be a good thing. It's not important to do anything if declining a challenge fails, since it will expire anyway when not accepted.

Backoff is disabled for HTTP errors with a status code below 500. See the [`is_final()`](https://github.com/ShailChoksi/lichess-bot/blob/298a98a145d5fb0c316ec5ec2a13c8d2891eb285/lichess.py#L55) function in lichess.py. I think the logic here is that these status codes indicate a request that was received but cannot be fulfilled.

**Comment by TheBlackPlague** [comment]
> It will fix this, but I think TheBlackPlague gets this error because they challenge other bots and their bot tries to decline the challenge (I would guess that `accept_bot` is false), causing an error because they can't decline their own challenges. We can add a check for challenges that the bot created and not decline them.
> [Here](https://github.com/ShailChoksi/lichess-bot/blob/master/lichess-bot.py#L238) we can change it to:
> ```python
> elif chlng.challenger_name != user_profile["username"]:
> ```
> or we can add this check inside [`is_supported`](https://github.com/ShailChoksi/lichess-bot/blob/master/lichess-bot.py#L231).
> 
> After enabling `only_bot`, when I challenged my human account, I got the same error, so this is the cause of the error.
> 
> Also, when I got this error lichess-bot quit instead of using backoff. backoff wouldn't have made a difference because it would just raise the same error again but I don't know if that is the expected behavior.

This would be the correct analysis as that is the case.
