### ISSUE TITLE
Automatically play when there is only one legal move

### ISSUE THREAD

**Issue by PaulJeFi** [ShailChoksi/lichess-bot#552]
A great improvement in this wonderful repo could be to play automatically without loosing time asking the engine when there is only one legal move.

**Comment by AttackingOrDefending** [comment]
Can you test #553?
This feature may result in your bot playing weaker because it can't ponder after an only move. Stockfish, for example, uses at most 500ms when there is [only one available move](https://github.com/official-stockfish/Stockfish/commit/04a320666efce725ef66d1a84aaef493a880153d). It would be better to ask the creator of the engine you are using to implement this in their engine, so the bot would be able to ponder.

**Comment by MarkZH** [comment]
Hi, @PaulJeFi! Thanks for the kind words.

I don't think many users would use this feature. Engines and their makers will have their own strategies for what to do when there is only one legal move. If an engine elects to make that move immediately, the time taken to communicate with the engine will be very small compared to latency with lichess, so there won't be any time saved. Like @AttackingOrDefending noted, this would also interfere with pondering.

**Comment by MarkZH** [comment]
I could be convinced otherwise.

**Comment by fabriciodosanjossilva** [comment]
I've been thinking about this request since it was posted. It seems to me that there is no reason for it to exist. If it is implemented, that's fine. No harm done.

But why would it be useful? The reason for the request, as stated by @PaulJeFi, is that time could be saved in the case of a single move position. Now, if there is a single move possible, then all the engine has to do is generate the moves and return the only one generated. This can be done in less than 1 ms even for the slowest engine. Usual engine search does this hundreds of thousands of times, possibly even millions of times. And this is the basic of an engine. So, if an engine can't do this, it wouldn't be an engine. If the engine takes dozens of ms to do this, than it would be so slow that it is hard to imagine. As noted by @MarkZH, Lichess API latency is not negligible. From my experience, an instant move by my engine (taken from cache), while using lichess-bot, is measured by Lichess as 150-200ms (subtracted from my playing time). So, for me, there is no point here. This feature would have usefulness to noone.

@PaulJeFi, if you have additional thoughts, feel free to present them. I could also be convinced otherwise. I'm still wondering why this feature is important to you.

**Comment by PaulJeFi** [comment]
Thanks for all this details and clarifications. I wanted this to be done because my engine is still searching, even when there is only one legal move. I will change this, but I believe that many engines work like mine worked. But I understand the Lichess API latency, so now I agree that what I thought was an improvement is actually not.
