### ISSUE TITLE
Can't use stdin to give a move to the bot

### ISSUE THREAD

**Issue by AttackingOrDefending** [ShailChoksi/lichess-bot#586]
From [discord](https://discord.com/channels/280713822073913354/1027102391490846751/1027102391490846751).

The user can't input a move to lichess-bot.
```python
class HumanMove(ExampleEngine):
    def search(self, board, *args):
        move = input("Give me a move: ")
        return PlayResult(Move.from_uci(move), None)
```

Exact message on discord:
> I am making a physical chess board where moves played on the board will be programmatically played against a friend on lichess. I cloned lichess-bot and messed around with running the RandomMove bot. My next step was to use input() to prompt the user for a uci move string and then play that move on lichess essentially making a lichess cli. However, I have not been able to read from stdin because I believe it is overwritten/closed by something in lichess-bot. Is there a way to get user input from my search method? This code works:
```python
class RandomMove(ExampleEngine):
    def search(self, board, *args):
        return PlayResult(random.choice(list(board.legal_moves)), None)
```
> However this does not:
```python
class RandomMove(ExampleEngine):
    def search(self, board, *args):
        mv = input("Give me a move")
        return PlayResult(random.choice(list(board.legal_moves)), None)
```
> I get this output repeated, when I run with input() in my code:
`INFO     Backing off play_game(...) for 19.9s (EOFError: EOF when reading a line)`
This is what happens if I print sys.stdin
`<_io.TextIOWrapper name=21 mode='r' encoding='UTF-8'>`
vs if I print sys.stdin 
`stdin <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>`
which makes me think sys.stdin is overwritten
If I try and do sys.stdin.readline() it just says file has been closed.
Is there some way to read stdin? Is there some trick where I can run a separate thread or process to read stdin and then return it in my search method? How could I make it so my "engine" is just reading a move from my command line?
I hope that makes sense and I really appreciate any help 🙂

**Comment by MarkZH** [comment]
I've done some experimenting, and it looks like `input()` only works from the main thread. Even calling `input()` from inside `play_game()` in licess-bot.py results in weird behavior. I don't think lichess-bot is the right place for testing a board interface due to it's inherent multithreadedness.

[This repository](https://github.com/Cqsi/lichs) is a program for playing lichess games on the console and playing moves by typing them into the console. It was linked from the [Lichess API reference](https://lichess.org/api#tag/Board). This could also serve as a basis for creating an interface to a physical board.

**Comment by ShailChoksi** [comment]
Would it be a good idea to extend the functionality of this repo to support the Board api? @MarkZH 

The API's are designed well and follow a similar pattern. It might be possible to re-use a lot of code and run it as a board API as well

**Comment by MarkZH** [comment]
I could see creating a new file: lichess-board.py. This could use code from lichess.py and model.py. I don't think most of the code in lichess-bot.py could be used since it's designed around automatically accepting/creating challenges with no user input. The lichess-board.py code could be much simpler since it would only have to handle one game at a time and be purely console based.

I don't know how we would implement actually communicating with the board peripheral nor how general we could make it; I would imagine that each device would have its own drivers and protocol and would require custom code. This is only a guess without some investigation.

**Comment by MarkZH** [comment]
I don't think we can do anything useful with the board API. Each peripheral maker will provide their own software to communicate via the API, so there's nothing for us to do. So, I'm closing this issue. If anyone thinks I'm wrong, please reopen.
