### ISSUE TITLE
Rate limit hangs the event loop

### ISSUE THREAD

**Issue by noobpwnftw** [ShailChoksi/lichess-bot#621]
For some reason since today, matchmaking challenges get rate limited even if they were made less than once per minute(daily quota somewhere?), which in turn blocks the event thread for 60s with every request.

**Comment by MarkZH** [comment]
I'm pretty sure there is a daily limit. In the past, I've seen in my logs a several hour period where every matchmaking request was rate limited followed by a resumption of requests going through.

**Comment by noobpwnftw** [comment]
Well, it sleeps the main thread for 60s which is not good.

**Comment by MarkZH** [comment]
Now, I understand the issue. This will take some work. First idea that comes to mind: replace `time.sleep(60)` with `self.rate_limit_timer = Timer(60)`. Then, inside `Lichess.api_post()` and `Lichess.api_get()`, return an empty or otherwise error response instead of calling the `self.session` methods until that timer expires.

**Comment by MarkZH** [comment]
@noobpwnftw Can you try out PR #622?
